### ISSUE TITLE
keep a changelog

### ISSUE THREAD

**Issue by sibelius** [DeeSnow97/koa-easy-ws#33]
can you provide a simple changelog for v2?

**Comment by b3nsn0w** [comment]
Yep, sure!

The major change is that `ws` has been moved to a peer dependency, that's why I bumped the major version, since it would be a breaking change. It will _technically_ work if you just upgrade to v2, especially because of the `package-lock.json` or `yarn.lock` keeping it there, but it would most likely inject a weird bug. On top of that, the peer dependency is for ws@8, not ws@7 which koa-easy-ws previously used, so refer to ws@8's breaking changes for that (but if you're fine with a warning ws@7 should continue to work).

Should probably add that to the readme as well.

**Comment by sibelius** [comment]
good enough for me, tks
